vim.g.mapleader = " "
vim.keymap.set("n", "<leader>b", vim.cmd.Ex)
vim.keymap.set("n", "<leader>t", ":NvimTreeToggle <CR>")
vim.keymap.set("n", "<leader>e", ":NvimTreeFocus <CR>")
vim.keymap.set("n", "<C-Right>", ":NvimTreeCollapse <CR>")
vim.keymap.set("n", "<C-Right>", ":BufferNext <CR>")
vim.keymap.set("n", "<C-Left>", ":BufferPrevious <CR>")
vim.keymap.set("n", "<leader>l", ":BufferNext <CR>")
vim.keymap.set("n", "<leader>h", ":BufferPrevious <CR>")
local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>f', builtin.find_files, { desc = 'Telescope find files' })
vim.keymap.set('n', '<C-p>', builtin.git_files, { desc = 'Telescope find git files' })
vim.keymap.set('n', '<leader>s', function()
	builtin.grep_string({search = vim.fn.input("Grep > ");})
 end)
